version: "3.8"

services:
  mysql:
    image: mysql:5.7
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: '1234'
  pypadmin:
    depends_on:
      - mysql
    image: phpmyadmin/phpmyadmin
    environment:
      PMA_HOST: mysql
    restart: always
    ports:
      - "8080:80"
  php-apache:
    build: ./php
    volumes:
      - ./htdocs:/var/www/html
      - ./setup_middlewares:/tmp/setup_middlewares
      - ./src:/usr/mochi/sandbox
    restart: always
    ports:
      - "80:80"
      - "8000:8000"
    depends_on:
      - mysql

volumes:
  db_data: {}
